# Generated by Django 5.2.13 on 2026-04-28 09:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('available', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('computer', 'Computer'), ('geography', 'Geography')], default='physics', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LabBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.CharField(choices=[('physics', 'Physics Lab'), ('chemistry', 'Chemistry Lab'), ('biology', 'Biology Lab'), ('computer', 'Computer Lab'), ('geography', 'Geography Lab')], max_length=50)),
                ('teacher_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.IntegerField(default=60)),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_class', models.CharField(max_length=50)),
                ('roll', models.CharField(max_length=20)),
                ('pin', models.CharField(max_length=10)),
                ('quantity', models.IntegerField(default=1)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('duration', models.IntegerField(default=60)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('booked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.equipment')),
            ],
            options={
                'ordering': ['-booking_date', '-booking_time'],
            },
        ),
    ]
